// Home page section schemas
export { default as businessSolutions } from './business-solutions'
export { default as streamline } from './streamline'
export { default as managePeople } from './manage-people'
export { default as hrBanner } from './hr-banner'
export { default as manageAssets } from './manage-assets'
export { default as assetsBanner } from './assets-banner'
export { default as documentManager } from './document-manager'
export { default as legalBanner } from './legal-banner'
export { default as financeAccounting } from './finance-accounting'
export { default as financeBanner } from './finance-banner'
export { default as powerAssets } from './power-assets'
export { default as powerBanner } from './power-banner'
export { default as businessAdministration } from './business-administration'
export { default as operationsBanner } from './operations-banner'
export { default as quoteBox } from './quote-box'
export { default as visualizedIllustration } from './visualized-illustration'
export { default as movingModules } from './moving-modules'
export { default as onePlatformBanner } from './one-platform-banner'
export { default as faqSection } from './faq-section'
export { default as dividerContent } from './divider-content'
export { default as hero } from './hero'
export { default as modulesCarousel } from './modules-carousel'
export { default as testimonial } from './testimonial'

// New document schemas
export { default as modulePageContent } from './modules-page-content'
export { default as footerData } from './footer-data'
export { default as functionalModulesList } from './functional-modules'
export { default as movingModulesData } from './moving-modules-data'