/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type MovingModulesData = {
  _id: string
  _type: 'movingModulesData'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  modulesGroupA?: Array<{
    name?: string
    icon?: string
    _type: 'movingModule'
    _key: string
  }>
  modulesGroupB?: Array<{
    name?: string
    icon?: string
    _type: 'movingModule'
    _key: string
  }>
}

export type FunctionalModulesList = {
  _id: string
  _type: 'functionalModulesList'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  modules?: Array<{
    name?: string
    link?: string
    icon?: string
    _type: 'functionalModule'
    _key: string
  }>
}

export type FooterData = {
  _id: string
  _type: 'footerData'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  brandPrimary?: string
  brandSecondary?: string
  brandLink?: string
  quickLinks?: Array<{
    title?: string
    links?: Array<{
      label?: string
      href?: string
      _type: 'quickLink'
      _key: string
    }>
    _type: 'quickLinkColumn'
    _key: string
  }>
  socialLinks?: Array<{
    icon?: 'instagram' | 'youtube' | 'twitter' | 'facebook' | 'linkedin'
    label?: string
    href?: string
    _type: 'socialLink'
    _key: string
  }>
  legalDisclaimer?: string
  riskWarning?: string
}

export type ModulePageContent = {
  _id: string
  _type: 'modulePageContent'
  _createdAt: string
  _updatedAt: string
  _rev: string
  moduleSlug?: string
  hero?: {
    title?: string
    description?: string
    backgroundImage?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    buttonText?: string
    buttonLink?: string
    dashboards?: Array<{
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }>
  }
  keyFeatures?: Array<{
    iconName?: string
    content?: string
    _type: 'keyFeature'
    _key: string
  }>
  mainCenter?: {
    header?: {
      title?: string
      description?: string
    }
    contents?: Array<{
      title?: string
      description?: string
      image?: {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      }
      link?: string
      _type: 'contentItem'
      _key: string
    }>
  }
  mainModuleBanner?: {
    content?: string
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  }
  industry?: {
    mainTitle?: string
    mainnDescription?: string
    industryItems?: Array<{
      iconName?: string
      title?: string
      description?: string
      image?: {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      }
      _type: 'industryItem'
      _key: string
    }>
  }
  subModuleBanner?: {
    title?: string
    content?: string
    buttonText?: string
    buttonLink?: string
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type DividerContent = {
  _type: 'dividerContent'
  text?: string
  link?: string
  showIcon?: boolean
}

export type FaqSection = {
  _type: 'faqSection'
  heading?: string
  description?: string
  faqs?: Array<{
    question?: string
    answer?: string
    _type: 'faq'
    _key: string
  }>
}

export type OnePlatformBanner = {
  _type: 'onePlatformBanner'
  backgroundImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  text?: string
  height?: number
}

export type MovingModules = {
  _type: 'movingModules'
  title?: string
  modulesGroupA?: Array<{
    name?: string
    icon?: string
    _type: 'module'
    _key: string
  }>
  modulesGroupB?: Array<{
    name?: string
    icon?: string
    _type: 'module'
    _key: string
  }>
}

export type VisualizedIllustration = {
  _type: 'visualizedIllustration'
  headingStart?: string
  headingHighlight?: string
  dashboardImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  backgroundImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type QuoteBox = {
  _type: 'quoteBox'
  quote?: string
  author?: string
  authorTitle?: string
}

export type OperationsBanner = {
  _type: 'operationsBanner'
  imageSrc?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heading?: string
  subheading?: string
  linkText?: string
  href?: string
  direction?: 'left' | 'right'
}

export type BusinessAdministration = {
  _type: 'businessAdministration'
  mainTitle?: string
  mainDescription?: string
  position?: 'left' | 'right'
  content?: Array<{
    title?: string
    description?: string
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    _type: 'contentItem'
    _key: string
  }>
}

export type PowerBanner = {
  _type: 'powerBanner'
  imageSrc?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heading?: string
  subheading?: string
  linkText?: string
  href?: string
  direction?: 'left' | 'right'
}

export type PowerAssets = {
  _type: 'powerAssets'
  mainTitle?: string
  mainDescription?: string
  position?: 'left' | 'right'
  content?: Array<{
    title?: string
    description?: string
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    _type: 'contentItem'
    _key: string
  }>
}

export type FinanceBanner = {
  _type: 'financeBanner'
  imageSrc?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heading?: string
  subheading?: string
  linkText?: string
  href?: string
  direction?: 'left' | 'right'
}

export type FinanceAccounting = {
  _type: 'financeAccounting'
  mainTitle?: string
  mainDescription?: string
  position?: 'left' | 'right'
  content?: Array<{
    title?: string
    description?: string
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    _type: 'contentItem'
    _key: string
  }>
}

export type LegalBanner = {
  _type: 'legalBanner'
  imageSrc?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heading?: string
  subheading?: string
  linkText?: string
  href?: string
  direction?: 'left' | 'right'
}

export type DocumentManager = {
  _type: 'documentManager'
  mainTitle?: string
  mainDescription?: string
  position?: 'left' | 'right'
  content?: Array<{
    title?: string
    description?: string
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    _type: 'contentItem'
    _key: string
  }>
}

export type AssetsBanner = {
  _type: 'assetsBanner'
  imageSrc?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heading?: string
  subheading?: string
  linkText?: string
  href?: string
  direction?: 'left' | 'right'
}

export type ManageAssets = {
  _type: 'manageAssets'
  mainTitle?: string
  mainDescription?: string
  content?: Array<{
    title?: string
    description?: string
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    _type: 'contentItem'
    _key: string
  }>
}

export type HrBanner = {
  _type: 'hrBanner'
  imageSrc?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heading?: string
  subheading?: string
  linkText?: string
  href?: string
  direction?: 'left' | 'right'
}

export type ManagePeople = {
  _type: 'managePeople'
  mainTitle?: string
  mainDescription?: string
  content?: Array<{
    title?: string
    description?: string
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    _type: 'contentItem'
    _key: string
  }>
}

export type Streamline = {
  _type: 'streamline'
  heading?: string
  highlightedText?: string
  buttonText?: string
  buttonLink?: string
  images?: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
}

export type BusinessSolutions = {
  _type: 'businessSolutions'
  heading?: string
  highlightedText?: string
  solutions?: Array<{
    emoji?: string
    title?: string
    description?: string
    _type: 'solution'
    _key: string
  }>
}

export type ModulesCarousel = {
  _type: 'modulesCarousel'
  slides?: Array<{
    title?: string
    buttonText?: string
    imageUrl?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    link?: string
    _type: 'slide'
    _key: string
  }>
}

export type Hero = {
  _type: 'hero'
  staticText?: string
  phrases?: Array<{
    text?: string
    className?: string
    _type: 'phrase'
    _key: string
  }>
  subtitle?: string
  primaryCtaText?: string
  primaryCtaLink?: string
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  sections?: Array<
    | ({
        _key: string
      } & Hero)
    | ({
        _key: string
      } & ModulesCarousel)
    | ({
        _key: string
      } & BusinessSolutions)
    | ({
        _key: string
      } & Streamline)
    | ({
        _key: string
      } & ManagePeople)
    | ({
        _key: string
      } & HrBanner)
    | ({
        _key: string
      } & ManageAssets)
    | ({
        _key: string
      } & AssetsBanner)
    | ({
        _key: string
      } & DocumentManager)
    | ({
        _key: string
      } & LegalBanner)
    | ({
        _key: string
      } & FinanceAccounting)
    | ({
        _key: string
      } & FinanceBanner)
    | ({
        _key: string
      } & PowerAssets)
    | ({
        _key: string
      } & PowerBanner)
    | ({
        _key: string
      } & BusinessAdministration)
    | ({
        _key: string
      } & OperationsBanner)
    | ({
        _key: string
      } & QuoteBox)
    | ({
        _key: string
      } & VisualizedIllustration)
    | ({
        _key: string
      } & MovingModules)
    | ({
        _key: string
      } & OnePlatformBanner)
    | ({
        _key: string
      } & FaqSection)
    | ({
        _key: string
      } & DividerContent)
  >
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  author?: string
  content?: string
  rating?: number
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  order?: number
  approveTestimonial?: boolean
}

export type SubModule = {
  _id: string
  _type: 'subModule'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  icon?: string
  slug?: Slug
  parentModule?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'module'
  }
  imageUrl?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  functionalFeatures?: {
    title?: string
    description?: string
    features?: Array<
      {
        _key: string
      } & FunctionalFeature
    >
  }
  hero?: {
    backgroundImage?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    title?: string
    description?: string
    buttonText?: string
    buttonLink?: string
    dashboardFunctions?: Array<{
      iconUrl?: string
      content?: string
      _type: 'dashboardFunction'
      _key: string
    }>
    dashboardStat?: {
      value?: string
      description?: string
    }
  }
  improve?: ImproveSection
  mainCenter?: {
    header?: {
      title?: string
      description?: string
    }
    mainDashboardImage?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    sideSections?: Array<{
      span?: string
      title?: string
      description?: string
      image?: {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      }
      list?: Array<{
        text?: string
        _type: 'listItem'
        _key: string
      }>
      _type: 'sideSection'
      _key: string
    }>
  }
  responsiveDesign?: {
    mobileImage?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    desktopImage?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    tabletImage?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  }
  FAQ?: Array<{
    question?: string
    answer?: string
    _type: 'faq'
    _key: string
  }>
  order?: number
}

export type ImproveSection = {
  _type: 'improveSection'
  title?: string
  description?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  content?: Array<{
    title?: string
    description?: string
    iconName?: string
    _type: 'lifecycleStep'
    _key: string
  }>
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Module = {
  _id: string
  _type: 'module'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  description?: string
  icon?: string
  order?: number
  subModules?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'subModule'
  }>
}

export type FunctionalFeature = {
  _type: 'functionalFeature'
  icon?: string
  title?: string
  content?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | MovingModulesData
  | FunctionalModulesList
  | FooterData
  | ModulePageContent
  | SanityImageCrop
  | SanityImageHotspot
  | DividerContent
  | FaqSection
  | OnePlatformBanner
  | MovingModules
  | VisualizedIllustration
  | QuoteBox
  | OperationsBanner
  | BusinessAdministration
  | PowerBanner
  | PowerAssets
  | FinanceBanner
  | FinanceAccounting
  | LegalBanner
  | DocumentManager
  | AssetsBanner
  | ManageAssets
  | HrBanner
  | ManagePeople
  | Streamline
  | BusinessSolutions
  | ModulesCarousel
  | Hero
  | HomePage
  | Testimonial
  | SubModule
  | ImproveSection
  | Slug
  | Module
  | FunctionalFeature
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
export declare const internalGroqTypeReferenceTo: unique symbol
