import homepage from './pages/homepage'
import { functionalFeature, improveSection, module, subModule } from './modules'
import {
  businessSolutions,
  streamline,
  managePeople,
  hrBanner,
  manageAssets,
  assetsBanner,
  documentManager,
  legalBanner,
  financeAccounting,
  financeBanner,
  powerAssets,
  powerBanner,
  businessAdministration,
  operationsBanner,
  quoteBox,
  visualizedIllustration,
  movingModules,
  onePlatformBanner,
  faqSection,
  dividerContent,
  hero,
  modulesCarousel,
  testimonial,
  // New document schemas
  modulePageContent,
  footerData,
  functionalModulesList,
  movingModulesData,
} from './home-schemas'

export const schemaTypes = [
  // Reusable object schemas
  functionalFeature,
  improveSection,
  // Documents
  module,
  subModule,
  // Home page
  testimonial,
  homepage,
  hero,
  modulesCarousel,
  businessSolutions,
  streamline,
  managePeople,
  hrBanner,
  manageAssets,
  assetsBanner,
  documentManager,
  legalBanner,
  financeAccounting,
  financeBanner,
  powerAssets,
  powerBanner,
  businessAdministration,
  operationsBanner,
  quoteBox,
  visualizedIllustration,
  movingModules,
  onePlatformBanner,
  faqSection,
  dividerContent,
  // New document types
  modulePageContent,
  footerData,
  functionalModulesList,
  movingModulesData,
]
