##!!!! Dont Touch Me Please, I'm dangerous
# prettier-ignore

name: PR Quality Checks
on:
  pull_request:
    branches: [main, release]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false # Don't install dependencies here

      # 2. Setup Node.js and caching
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      # 3. Install dependencies
      # We use --frozen-lockfile to ensure we use the exact versions specified in the lockfile
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 4. Fix all eslint fixable lint errors
      - name: Fix Linting Issues
        run: pnpm run lint:fix

      # 5. Run ESLint Check
      - name: Run Linting Checks
        run: pnpm run lint

      # 6. Run Build Check (Ensure the TypeScript/JS compiles successfully)
      - name: Run Build
        run: pnpm run build
